# Translations template for eon.
#
# (c) Copyright 2013-2017 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: eon 8.0.0.20\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2013-10-15 18:04+0530\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 0.9.6\n"

#: eon/api/middleware/context.py:17
msgid "Role used to identify an authenticated user as administrator."
msgstr "用于将经过验证的用户指定为管理员的角色。"

#: eon/api/middleware/context.py:32
msgid "Unable to retrieve request id from context"
msgstr "无法从上下文中检索请求 ID"

#: eon/api/middleware/context.py:85
msgid "Invalid service catalog json."
msgstr "无效的服务目录 JSON。"

#: eon/api/middleware/version_negotiation.py:31
#, python-format
msgid "Determining version of request: %(method)s %(path)s Accept: %(accept)s"
msgstr "正在确定请求版本:%(method)s %(path)s 接受:%(accept)s"

#: eon/api/middleware/version_negotiation.py:42
msgid "Using url versioning"
msgstr "使用 URL 版本控制"

#: eon/api/middleware/version_negotiation.py:49
msgid "Unknown version. Returning version choices."
msgstr "未知版本。正在返回版本选项。"

#: eon/api/middleware/version_negotiation.py:54
#, python-format
msgid "Matched version: v%d"
msgstr "匹配的版本:v%d"

#: eon/api/v1/controller.py:20
#, python-format
msgid "Validating required attributes...Got: %s, Required attributes: %s"
msgstr "正在验证所需的属性...获取的是:%s，所需的属性:%s"

#: eon/api/v1/esx_proxy.py:75
msgid "Fetching list of all registered ESX-Proxy"
msgstr "正在获取注册的 ESX 代理列表"

#: eon/api/v1/esx_proxy.py:99
#, python-format
msgid "Validating ESX-Proxy before creating, ESX-Proxy: %s"
msgstr "在创建之前，正在验证 ESX 代理，ESX 代理:%s"

#: eon/api/v1/esx_proxy.py:104
#: eon/api/v1/esx_proxy.py:119
#, python-format
msgid "ESX-Proxy by name (%s) already exists"
msgstr "具有名称(%s)的 ESX 代理已存在"

#: eon/api/v1/esx_proxy.py:107
#: eon/api/v1/esx_proxy.py:122
#, python-format
msgid "ESX-Proxy by name (%s) not found"
msgstr "找不到具有名称 %s 的 ESX 代理"

#: eon/api/v1/esx_proxy.py:114
#, python-format
msgid "Validating ESX-Proxy before updating, ESX-Proxy id: %s"
msgstr "在更新之前，正在验证 ESX 代理，ESX 代理 ID:%s"

#: eon/api/v1/esx_proxy.py:129
#, python-format
msgid "Validating ESX-Proxy(id: %s) before deleting"
msgstr "在删除之前，正在验证 ESX 代理(ID:%s)"

#: eon/api/v1/esx_proxy.py:137
#, python-format
msgid "Cannot delete! there are active resource(s) associated to vCenter (%s)"
msgstr "无法删除! 具有与 vCenter (%s)关联的活动资源"

#: eon/api/v1/esx_proxy.py:141
#, python-format
msgid "Failed to delete %s"
msgstr "无法删除 %s"

#: eon/api/v1/esx_proxy.py:164
#, python-format
msgid "Registering ESX-Proxy, context: %s, ESX-Proxy data: %s"
msgstr "正在注册 ESX 代理，上下文:%s，ESX 代理数据:%s"

#: eon/api/v1/esx_proxy.py:168
#, python-format
msgid "Required attributes validation failed: %s"
msgstr "所需的属性验证失败:%s"

#: eon/api/v1/esx_proxy.py:176
#, python-format
msgid "Cannot create ESX-Proxy reason: %s"
msgstr "无法创建 ESX 代理，原因:%s"

#: eon/api/v1/esx_proxy.py:181
msgid "Successfully created esx_proxy"
msgstr "已成功创建 ESX 代理"

#: eon/api/v1/esx_proxy.py:186
msgid "ESX-Proxy with identifier already exists!"
msgstr "具有标识符的 ESX 代理已存在!"

#: eon/api/v1/esx_proxy.py:190
#, python-format
msgid "Failed to add esx_proxy metadata. Got error: %(e)s"
msgstr "无法添加 ESX 代理元数据。出现错误:%(e)s"

#: eon/api/v1/esx_proxy.py:204
#, python-format
msgid "Updating ESX-Proxy, context: %s"
msgstr "正在更新 ESX 代理，上下文:%s"

#: eon/api/v1/esx_proxy.py:205
#, python-format
msgid "ESX-Proxy data: %s"
msgstr "ESX 代理数据:%s"

#: eon/api/v1/esx_proxy.py:210
#, python-format
msgid "Required attribute validation failed: %s"
msgstr "所需的属性验证失败:%s"

#: eon/api/v1/esx_proxy.py:216
#, python-format
msgid "Cannot update ESX-Proxy(ID: %s) reason: %s"
msgstr "无法更新 ESX 代理(ID:%s)，原因:%s"

#: eon/api/v1/esx_proxy.py:222
msgid "Successfully updated esx_proxy"
msgstr "已成功更新 ESX 代理"

#: eon/api/v1/esx_proxy.py:228
#, python-format
msgid "Failed to update vCenter. Got error: %(e)s"
msgstr "无法更新 vCenter。出现错误:%(e)s"

#: eon/api/v1/esx_proxy.py:246
#, python-format
msgid "Deleting ESX-Proxy, context: %s id: %s"
msgstr "正在删除 ESX 代理，上下文:%s ID:%s"

#: eon/api/v1/esx_proxy.py:250
#, python-format
msgid "Cannot delete ESX-Proxy(ID: %s) reason: %s"
msgstr "无法删除 ESX 代理(ID:%s)，原因:%s"

#: eon/api/v1/esx_proxy.py:255
msgid "Successfully destroyed esx_proxy"
msgstr "已成功销毁 ESX 代理"

#: eon/api/v1/esx_proxy.py:259
#, python-format
msgid "Failed to delete esx_proxy. Got error: %(e)s"
msgstr "无法删除 ESX 代理。出现错误:%(e)s"

#: eon/api/v1/esx_proxy.py:275
#: eon/api/v1/managed_entity.py:629
#, python-format
msgid "Store for scheme %s not found"
msgstr "找不到方案 %s 的存储"

#: eon/api/v1/managed_entity.py:41
msgid "The maximum number of clusters supported per proxy vm"
msgstr "每个代理 VM 支持的最大群集数"

#: eon/api/v1/managed_entity.py:89
#, python-format
msgid "Unable to display the resources:got the error : %s"
msgstr "无法显示资源，出现错误:%s"

#: eon/api/v1/managed_entity.py:121
#, python-format
msgid "Registering resource, context: %s, vCenter: %s, Resource: %s"
msgstr "正在注册资源，上下文:%s，vCenter:%s，资源:%s"

#: eon/api/v1/managed_entity.py:139
#, python-format
msgid "ESX-Proxy VM %s successfully created "
msgstr "已成功创建 ESX 代理 VM %s"

#: eon/api/v1/managed_entity.py:164
msgid "Checking if max supported clusters limit reached"
msgstr "正在检查是否达到最大支持的群集限制"

#: eon/api/v1/managed_entity.py:166
msgid "Max supported clusters limit reached, Creating"
msgstr "已达到最大支持的群集限制，正在创建"

#: eon/api/v1/managed_entity.py:170
#, python-format
msgid "Using existing ESX-Proxy: %s"
msgstr "使用现有的 ESX 代理:%s"

#: eon/api/v1/managed_entity.py:204
#, python-format
msgid "Unable to display the resource:got the error : %s"
msgstr "无法显示资源: 出现错误: %s"

#: eon/api/v1/managed_entity.py:219
#, python-format
msgid "state_change for resource: %s state = %s"
msgstr "资源的状态更改:%s 状态 = %s"

#: eon/api/v1/managed_entity.py:256
#, python-format
msgid "Import resource %s "
msgstr "导入资源 %s"

#: eon/api/v1/managed_entity.py:265
#, python-format
msgid "Imported resource %s and imported id is %s"
msgstr "已导入资源 %s，导入的 ID 为 %s"

#: eon/api/v1/managed_entity.py:279
#, python-format
msgid "Imported resource %s and sending response %s"
msgstr "已导入资源 %s，正在发送响应 %s"

#: eon/api/v1/managed_entity.py:287
#, python-format
msgid "Import resource information passed is %s"
msgstr "传递的导入资源信息是 %s"

#: eon/api/v1/managed_entity.py:293
#, python-format
msgid "Resource name %s is already importedresource_name"
msgstr "已导入资源名称 %s"

#: eon/api/v1/managed_entity.py:302
#, python-format
msgid "Unable to import the resource  (%s) Got error: %s"
msgstr "无法导入资源(%s)，出现错误:%s"

#: eon/api/v1/managed_entity.py:355
#, python-format
msgid "Resource name %s is not imported"
msgstr "未导入资源名称 %s"

#: eon/api/v1/managed_entity.py:358
#, python-format
msgid "Found imported resource %s"
msgstr "找到导入的资源 %s"

#: eon/api/v1/managed_entity.py:362
#, python-format
msgid "Resource name %s is already activated or in the process of activation"
msgstr "已激活或正在激活资源名称 %s"

#: eon/api/v1/managed_entity.py:366
#, python-format
msgid "Found valid imported resource %s"
msgstr "找到导入的有效资源 %s"

#: eon/api/v1/managed_entity.py:369
#, python-format
msgid "properties for the cluster: %s"
msgstr "群集的属性:%s"

#: eon/api/v1/managed_entity.py:376
#, python-format
msgid "DC for resource %s is %s"
msgstr "资源 %s 的 DC 是 %s"

#: eon/api/v1/managed_entity.py:394
#, python-format
msgid "Switch is not configured for the cluster %s in datacenter %s"
msgstr "没有为群集 %s 配置交换机，数据中心= %s"

#: eon/api/v1/managed_entity.py:407
#, python-format
msgid "cluster data = %s"
msgstr "群集数据 = %s"

#: eon/api/v1/managed_entity.py:418
#, python-format
msgid ""
"Switch %s has configuration errors for the cluster %s in datacenter %s. "
"Errors = %s"
msgstr ""
"交换机 %s 出现配置错误，群集= %s，数据中心= %s。"
"错误 = %s"

#: eon/api/v1/managed_entity.py:452
#, python-format
msgid " Resource entity details: %s "
msgstr " 资源实体详细信息:%s "

#: eon/api/v1/managed_entity.py:490
#, python-format
msgid "Unable to activate the cluster %s Got the error : %s"
msgstr "无法激活群集 %s，出现错误:%s"

#: eon/api/v1/managed_entity.py:499
#, python-format
msgid "remove_resource %s %s %s"
msgstr "删除资源 %s %s %s"

#: eon/api/v1/managed_entity.py:525
#, python-format
msgid "Removed resource %s and sending response %s"
msgstr "已删除资源 %s，正在发送响应 %s"

#: eon/api/v1/managed_entity.py:528
#, python-format
msgid "Cannot remove resource (%s) in since it is not imported."
msgstr "无法删除资源(%s)，因为未导入该资源。"

#: eon/api/v1/managed_entity.py:539
#, python-format
msgid "Un-Registering resource id: %s"
msgstr "正在取消注册资源 ID:%s"

#: eon/api/v1/managed_entity.py:581
#, python-format
msgid "Successfully unregistered resource [%s]"
msgstr "已成功取消注册资源 [%s]"

#: eon/api/v1/managed_entity.py:588
#, python-format
msgid "Unable to unregister resource %sGot error: %s"
msgstr "无法取消注册资源 %sGot，错误:%s"

#: eon/api/v1/managed_entity.py:609
msgid "Successfully destroyed resource_entity"
msgstr "已成功销毁资源实体"

#: eon/api/v1/managed_entity.py:613
#, python-format
msgid "Failed to delete vCenter. Got error: %(e)s"
msgstr "无法删除 vCenter。出现错误:%(e)s"

#: eon/api/v1/managed_entity.py:661
msgid "ManagedEntitySerializer"
msgstr "托管实体序列化程序"

#: eon/api/v1/vcenter.py:124
msgid "Fetching list of all registered vcenters"
msgstr "正在获取所有注册的 vCenter 的列表"

#: eon/api/v1/vcenter.py:128
#, python-format
msgid "Error while listing the vCenters : %s"
msgstr "在列出 vCenter 时出错: %s"

#: eon/api/v1/vcenter.py:167
#, python-format
msgid "Unable to list the details of vCenter,Got error %s"
msgstr "无法列出 vCenter 详细信息，出现错误 %s"

#: eon/api/v1/vcenter.py:232
#, python-format
msgid "Unable to display the vcenter details.got the error : %s"
msgstr "无法显示 vCenter 详细信息。出现错误: %s"

#: eon/api/v1/vcenter.py:238
#, python-format
msgid "Details of vcenter:  %s has been returned"
msgstr "vCenter 详细信息:已返回 %s"

#: eon/api/v1/vcenter.py:289
msgid "ip_address"
msgstr "IP 地址"

#: eon/api/v1/vcenter.py:295
#, python-format
msgid "Could not retrieve vCenter %s"
msgstr "无法检索 vCenter %s"

#: eon/api/v1/vcenter.py:300
#, python-format
msgid ""
"Registration of vCenter failed.\n"
"This could be due to invalid credentials or the vCenter server %s is "
"unreachable.ip_address"
msgstr ""
"vCenter 注册失败。\n"
"原因可能是凭据无效或无法访问 vCenter 服务器 %s 的"
" IP 地址"

#: eon/api/v1/vcenter.py:313
#, python-format
msgid "vCenter with id [%s] does not exist"
msgstr "具有 ID [%s] 的 vCenter 不存在"

#: eon/api/v1/vcenter.py:316
#, python-format
msgid "vCenter with id (%s) does not exist"
msgstr "具有 ID (%s)的 vCenter 不存在"

#: eon/api/v1/vcenter.py:322
#, python-format
msgid "Check vCenter connectivity since IP has changed old IP = %s new IP = %s"
msgstr "检查 vCenter 连接，因为 IP 已更改，旧 IP = %s，新 IP = %s"

#: eon/api/v1/vcenter.py:344
#: eon/api/v1/vcenter.py:595
#, python-format
msgid "Configured settings = %s"
msgstr "配置的设置 = %s"

#: eon/api/v1/vcenter.py:357
#, python-format
msgid ""
"The datacenter %s has cluster(s) activated with different switch name "
"(%s) and therefore the switch name cannot be modified"
msgstr ""
"数据中心 %s 使用不同的交换机名称(%s)激活了群集，"
"因此，无法修改交换机名称"

#: eon/api/v1/vcenter.py:371
#, python-format
msgid "Fail to delete, there are active Resource(s) associated to vCenter (ID %s)"
msgstr "无法删除，存在与 vCenter (ID %s) 关联的活动资源"

#: eon/api/v1/vcenter.py:376
#, python-format
msgid "Could not find vCenter %s %s"
msgstr "找不到 vCenter %s %s"

#: eon/api/v1/vcenter.py:438
#, python-format
msgid "vShield IP %s is invalid for vCenter %s "
msgstr "vShield IP %s 对于 vCenter %s 无效"

#: eon/api/v1/vcenter.py:441
#, python-format
msgid "Error validating vShield credentials : %s"
msgstr "在验证 vShield 凭据时出错: %s"

#: eon/api/v1/vcenter.py:453
#, python-format
msgid "The list of proxy associated to the vCenter %s"
msgstr "与 vCenter %s 关联的代理列表"

#: eon/api/v1/vcenter.py:469
#, python-format
msgid "Fetch all resources associated to ESX-Proxy(ID: %s)"
msgstr "获取与 ESX 代理(ID:%s)"

#: eon/api/v1/vcenter.py:478
#, python-format
msgid "Returning...Resource-Name: %s, Resource-Path: %s"
msgstr "正在返回...资源名称:%s，资源路径:%s"

#: eon/api/v1/vcenter.py:503
#, python-format
msgid "Registering vcenter, context: %s"
msgstr "正在注册 vCenter，上下文:%s"

#: eon/api/v1/vcenter.py:508
#, python-format
msgid "Required attributes %s"
msgstr "必需属性 %s"

#: eon/api/v1/vcenter.py:521
msgid "All vShield credentials must be specified"
msgstr "必须指定所有 vShield 凭据"

#: eon/api/v1/vcenter.py:544
#, python-format
msgid "Successfully added the vcenter %s"
msgstr "已成功添加 vCenter %s"

#: eon/api/v1/vcenter.py:552
msgid "vCenter with identifier already exists!"
msgstr "具有标识符的 vCenter 已存在!"

#: eon/api/v1/vcenter.py:556
#, python-format
msgid "Unable to display the vcenter details:got the error : %s"
msgstr "无法显示 vCenter 详细信息，出现错误:%s"

#: eon/api/v1/vcenter.py:571
#, python-format
msgid "Updating vcenter, context: %s"
msgstr "正在更新 vCenter，上下文:%s"

#: eon/api/v1/vcenter.py:574
#, python-format
msgid "vCenter-Data: name: %s, username: %s, ip_address: %s, port: %s"
msgstr "vCenter 数据:名称:%s，用户名:%s，IP 地址:%s，端口:%s"

#: eon/api/v1/vcenter.py:607
#, python-format
msgid "Reconfigured switch settings = %s"
msgstr "重新配置的交换机设置 = %s"

#: eon/api/v1/vcenter.py:612
#, python-format
msgid "Updating settings = %s"
msgstr "正在更新设置 = %s"

#: eon/api/v1/vcenter.py:619
msgid "Successfully updated vcenter settings"
msgstr "已成功更新 vCenter 设置"

#: eon/api/v1/vcenter.py:624
#, python-format
msgid "Response for update vCenter %s"
msgstr "更新 vCenter %s 的响应"

#: eon/api/v1/vcenter.py:628
#, python-format
msgid "Failed to update vCenter. Got error: %s"
msgstr "无法更新 vCenter。出现错误:%s"

#: eon/api/v1/vcenter.py:647
#, python-format
msgid "Unregister vcenter id: %s"
msgstr "取消注册 vCenter ID:%s"

#: eon/api/v1/vcenter.py:654
msgid "Successfully deleted vcenter"
msgstr "已成功删除 vCenter"

#: eon/api/v1/vcenter.py:658
#, python-format
msgid "Failed to delete vCenter. Got error: %s"
msgstr "无法删除 vCenter。出现错误:%s"

#: eon/common/config.py:23
msgid ""
"Partial name of a pipeline in your paste configuration file with the "
"service name removed. For example, if your paste section name is "
"[pipeline:isc-api-keystone] use the value \"keystone\""
msgstr ""
"粘贴配置文件中删除了服务名称"
"的部分管道名称。例如，如果粘贴部分名称为 "
"[pipeline:isc-api-keystone]，则使用值“keystone”"

#: eon/common/config.py:29
msgid "Name of the paste configuration file."
msgstr "粘贴配置文件的名称。"

#: eon/common/config.py:33
msgid "Python module path of data access API"
msgstr "数据访问 API 的 Python 模块路径"

#: eon/common/config.py:35
msgid ""
"Default value for the number of items returned by a request if not "
"specified explicitly in the request"
msgstr ""
"未在请求中明确指定时，请求返回的"
"项目数的默认值"

#: eon/common/config.py:38
msgid "Maximum permissible number of items that could be returned by a request"
msgstr "请求可返回的最大允许项目数"

#: eon/common/config.py:41
msgid "Deploy the v1 OpenStack Images API. "
msgstr "部署 v1 OpenStack 映像 API。"

#: eon/common/config.py:43
msgid "The hostname/IP of the pydev process listening for debug connections"
msgstr "侦听调试连接的 pydev 进程的主机名/IP"

#: eon/common/config.py:46
msgid "The port on which a pydev process is listening for connections."
msgstr "pydev 进程侦听连接时使用的端口。"

#: eon/common/config.py:49
msgid ""
"Key used for encrypting sensitive metadata while talking to the registry "
"or database."
msgstr ""
"与注册表或数据库通信时，用于加密敏感元数据"
"的密钥。"

#: eon/common/config.py:111
msgid "Invalid syslog facility"
msgstr "syslog 工具无效"

#: eon/common/config.py:176
#, python-format
msgid "Loading %(app_name)s from %(conf_file)s"
msgstr "正在加载 %(app_name)s (从 %(conf_file)s 中)"

#: eon/common/config.py:187
#, python-format
msgid ""
"Unable to load %(app_name)s from configuration file %(conf_file)s.\n"
"Got: %(e)r"
msgstr ""
"无法加载 %(app_name)s (从配置文件 %(conf_file)s 中)。\n"
"获取的是:%(e)r"

#: eon/common/exception.py:25
msgid "An unknown exception occurred"
msgstr "发生未知异常"

#: eon/common/exception.py:43
msgid "Missing required argument."
msgstr "缺少所需的参数。"

#: eon/common/exception.py:47
#, python-format
msgid "Missing required credential: %(required)s"
msgstr "缺少所需的凭据:%(required)s"

#: eon/common/exception.py:51
#, python-format
msgid ""
"Incorrect auth strategy, expected \"%(expected)s\" but received "
"\"%(received)s\""
msgstr ""
"不正确的身份验证策略，应为 \"%(expected)s\"，但收到 "
"\"%(received)s\""

#: eon/common/exception.py:56
msgid "An object with the specified identifier was not found."
msgstr "找不到具有指定标识符的对象。"

#: eon/common/exception.py:60
#, python-format
msgid "Unknown scheme '%(scheme)s' found in URI"
msgstr "在 URI 中找到未知方案“%(scheme)s”"

#: eon/common/exception.py:64
msgid "The Store URI was malformed."
msgstr "存储 URI 的格式不正确。"

#: eon/common/exception.py:68
msgid "An object with the same identifier already exists."
msgstr "具有相同标识符的对象已存在。"

#: eon/common/exception.py:72
#, python-format
msgid "Connect error/bad request to Auth service at URL %(url)s."
msgstr "将错误/不正确的请求连接到 URL %(url)s 处的授权服务。"

#: eon/common/exception.py:76
#, python-format
msgid "Auth service at URL %(url)s not found."
msgstr "找不到 URL %(url)s 处的授权服务。"

#: eon/common/exception.py:80
msgid "Authorization failed."
msgstr "授权失败。"

#: eon/common/exception.py:84
msgid "You are not authenticated."
msgstr "您未进行身份验证。"

#: eon/common/exception.py:88
#: eon/common/exception.py:93
msgid "You are not authorized to complete this action."
msgstr "您无权完成此操作。"

#: eon/common/exception.py:97
msgid "Data supplied was not valid."
msgstr "提供的数据无效。"

#: eon/common/exception.py:101
msgid "Sort key supplied was not valid."
msgstr "提供的排序键无效。"

#: eon/common/exception.py:105
msgid "Unable to filter using the specified range."
msgstr "无法使用指定的范围进行过滤。"

#: eon/common/exception.py:109
#, python-format
msgid "Attribute '%(property)s' is read-only."
msgstr "属性“%(property)s”是只读的。"

#: eon/common/exception.py:113
#, python-format
msgid "Attribute '%(property)s' is reserved."
msgstr "属性“%(property)s”是保留的。"

#: eon/common/exception.py:117
#, python-format
msgid "Redirecting to %(uri)s for authorization."
msgstr "正在重定向到 %(uri)s 以进行授权。"

#: eon/common/exception.py:121
msgid "There was an error migrating the database."
msgstr "在迁移数据库时出错。"

#: eon/common/exception.py:125
msgid "There was an error connecting to a server"
msgstr "在连接到服务器时出错"

#: eon/common/exception.py:129
msgid "There was an error configuring the client."
msgstr "在配置客户端时出错。"

#: eon/common/exception.py:133
#, python-format
msgid ""
"The request returned a 302 Multiple Choices. This generally means that "
"you have not included a version indicator in a request URI.\n"
"\n"
"The body of response returned:\n"
"%(body)s"
msgstr ""
"请求返回了 302 多个选项。这通常意味着，"
"未在请求 URI 中包含版本指示符。\n"
"\n"
"返回的响应正文:\n"
"%(body)s"

#: eon/common/exception.py:139
#, python-format
msgid ""
"The request returned a 413 Request Entity Too Large. This generally means"
" that rate limiting or a quota threshold was breached.\n"
"\n"
"The response body:\n"
"%(body)s"
msgstr ""
"请求返回了 413 请求实体太大。这通常意味着，"
"超过了速率限制或配额阈值。\n"
"\n"
"响应正文:\n"
"%(body)s"

#: eon/common/exception.py:150
msgid ""
"The request returned 503 Service Unavilable. This generally occurs on "
"service overload or other transient outage."
msgstr ""
"请求返回了 503 服务不可用。在服务过载"
"或其它暂时性中断时，通常会出现该问题。"

#: eon/common/exception.py:161
msgid "The request returned 500 Internal Server Error."
msgstr "请求返回了 500 内部服务器错误。"

#: eon/common/exception.py:165
#, python-format
msgid ""
"The request returned an unexpected status: %(status)s.\n"
"\n"
"The response body:\n"
"%(body)s"
msgstr ""
"请求返回了意外状态:%(status)s。\n"
"\n"
"响应正文:\n"
"%(body)s"

#: eon/common/exception.py:170
#, python-format
msgid "Invalid content type %(content_type)s"
msgstr "无效的内容类型 %(content_type)s"

#: eon/common/exception.py:174
#, python-format
msgid "Registry was not configured correctly on API server. Reason: %(reason)s"
msgstr "未在 API 服务器上正确配置注册表。原因:%(reason)s"

#: eon/common/exception.py:179
#, python-format
msgid "Store %(store_name)s could not be configured correctly. Reason: %(reason)s"
msgstr "无法正确配置存储 %(store_name)s。原因:%(reason)s"

#: eon/common/exception.py:184
#, python-format
msgid ""
"Driver %(driver_name)s could not be configured correctly. Reason: "
"%(reason)s"
msgstr ""
"无法正确配置驱动程序 %(driver_name)s。原因:"
"%(reason)s"

#: eon/common/exception.py:189
#, python-format
msgid "Maximum redirects (%(redirects)s) was exceeded."
msgstr "超过最大重定向数(%(redirects)s)。"

#: eon/common/exception.py:193
msgid "Received invalid HTTP redirect."
msgstr "收到无效的 HTTP 重定向。"

#: eon/common/exception.py:197
msgid "Response from Keystone does not contain a isc endpoint."
msgstr "来自 Keystone 的响应不包含 ISC 端点。"

#: eon/common/exception.py:201
#, python-format
msgid "Server worker creation failed: %(reason)s."
msgstr "服务器工作线程创建失败:%(reason)s。"

#: eon/common/exception.py:205
#, python-format
msgid "Unable to load schema: %(reason)s"
msgstr "无法加载架构:%(reason)s"

#: eon/common/exception.py:209
#, python-format
msgid "Provided object does not match schema '%(schema)s': %(reason)s"
msgstr "提供的对象与架构“%(schema)s”不匹配:%(reason)s"

#: eon/common/exception.py:214
#, python-format
msgid "Provided header feature is unsupported: %(feature)s"
msgstr "不支持提供的标头功能:%(feature)s"

#: eon/common/exception.py:218
#, python-format
msgid "%(cls)s exception was raised in the last rpc call: %(val)s"
msgstr "在上次 RPC 调用中引发 %(cls)s 异常:%(val)s"

#: eon/common/exception.py:222
#, python-format
msgid "PAVMM Create VM REST api return error: %(status)s"
msgstr "PAVMM 创建 VM REST API 返回错误:%(status)s"

#: eon/common/exception.py:226
#, python-format
msgid "PAVMM Start VM REST api return error: %(status)s"
msgstr "PAVMM 启动 VM REST API 返回错误:%(status)s"

#: eon/common/exception.py:229
#, python-format
msgid "PAVMM Delete VM REST api return error: %(status)s"
msgstr "PAVMM 删除 VM REST API 返回错误:%(status)s"

#: eon/common/exception.py:232
#, python-format
msgid "Nova compute service fail to start error: %(status)s"
msgstr "Nova 计算服务无法启动，错误:%(status)s"

#: eon/common/jsonutils.py:84
#, python-format
msgid "Max serialization depth exceeded on object: %d %s"
msgstr "已超过对象上的最大序列化深度:%d %s"

#: eon/common/log.py:110
#, python-format
msgid "Deprecated: %s"
msgstr "已过时:%s"

#: eon/common/log.py:237
#, python-format
msgid "syslog facility must be one of: %s"
msgstr "syslog 工具必须是以下值之一:%s"

#: eon/common/log.py:425
#, python-format
msgid "Fatal call to deprecated config: %(msg)s"
msgstr "对过时的配置的调用出现严重错误:%(msg)s"

#: eon/common/rpc.py:99
msgid "Request must be a list of commands"
msgstr "请求必须是一个命令列表"

#: eon/common/rpc.py:104
#, python-format
msgid "Bad Command: %s"
msgstr "错误的命令:%s"

#: eon/common/rpc.py:111
#, python-format
msgid "Wrong command structure: %s"
msgstr "错误的命令结构:%s"

#: eon/common/rpc.py:120
msgid "Command not found"
msgstr "找不到命令"

#: eon/common/rpc.py:142
#, python-format
msgid ""
"RPC Call Error: %(val)s\n"
"%(tb)s"
msgstr ""
"RPC 调用错误:%(val)s\n"
"%(tb)s"

#: eon/common/utils.py:51
msgid "Read-only access"
msgstr "只读访问"

#: eon/common/utils.py:95
#, python-format
msgid "Invalid backend: %s"
msgstr "无效的后端:%s"

#: eon/common/utils.py:151
msgid "Token is not specified or is not valid"
msgstr "未指定令牌或无效"

#: eon/common/utils.py:156
msgid "The authorization key is not present"
msgstr "授权密钥不存在"

#: eon/common/utils.py:160
msgid "Authorization token is empty or not present"
msgstr "授权令牌为空或不存在"

#: eon/common/utils.py:169
#, python-format
msgid "Authorization check response is %s"
msgstr "授权检查响应是 %s"

#: eon/common/utils.py:170
#, python-format
msgid "Authorization check componentID is %s"
msgstr "授权检查组件 ID 是 %s"

#: eon/common/wsgi.py:37
msgid ""
"Address to bind the server.  Useful when selecting a particular network "
"interface."
msgstr ""
"将服务器绑定到的地址。在选择特定网络接口时"
"非常有用。"

#: eon/common/wsgi.py:40
msgid "The port on which the server will listen."
msgstr "服务器将侦听的端口。"

#: eon/common/wsgi.py:45
msgid "The backlog value that will be used when creating the TCP listener socket."
msgstr "在创建 TCP 侦听程序套接字时使用的积压工作值。"

#: eon/common/wsgi.py:48
msgid ""
"The value for the socket option TCP_KEEPIDLE.  This isthe time in seconds"
" that the connection must be idle before TCP starts sending keepalive "
"probes."
msgstr ""
"套接字选项 TCP_KEEPIDLE 的值。这是 TCP 开始"
"发送保持连接探测之前连接处于空闲状态"
"的时间(秒)。"

#: eon/common/wsgi.py:51
msgid "CA certificate file to use to verify connecting clients."
msgstr "用于验证连接客户端的 CA 证书文件。"

#: eon/common/wsgi.py:53
msgid "Certificate file to use when starting API server securely."
msgstr "在安全地启动 API 服务器时使用的证书文件。"

#: eon/common/wsgi.py:55
msgid "Private key file to use when starting API server securely."
msgstr "在安全地启动 API 服务器时使用的私钥文件。"

#: eon/common/wsgi.py:60
msgid ""
"The number of child process workers that will be created to service API "
"requests."
msgstr ""
"为处理 API 请求而创建的子进程"
"工作线程数。"

#: eon/common/wsgi.py:113
msgid ""
"When running server in SSL mode, you must specify both a cert_file and "
"key_file option value in your configuration file"
msgstr ""
"在 SSL 模式下运行服务器时，必须在配置文件中"
"指定 cert_file 和 key_file 选项值"

#: eon/common/wsgi.py:151
#, python-format
msgid "Could not bind to %s:%s after trying for 30 seconds"
msgstr "无法绑定到 %s:%s在尝试 30 秒后"

#: eon/common/wsgi.py:223
#, python-format
msgid "Starting %d workers"
msgstr "正在启动 %d 个工作线程"

#: eon/common/wsgi.py:238
#, python-format
msgid "Removing dead child %s"
msgstr "正在删除失效的子项 %s"

#: eon/common/wsgi.py:241
#, python-format
msgid "Not respawning child %d, cannot recover from termination"
msgstr "未重新生成子项 %d，无法从终止中恢复"

#: eon/common/wsgi.py:245
msgid "All workers have terminated. Exiting"
msgstr "已终止所有工作线程。正在退出"

#: eon/common/wsgi.py:253
msgid "Caught keyboard interrupt. Exiting."
msgstr "已捕获键盘中断。正在退出。"

#: eon/common/wsgi.py:257
msgid "Exited"
msgstr "已退出"

#: eon/common/wsgi.py:279
#, python-format
msgid "Child %d exiting normally"
msgstr "子项 %d 正在正常退出"

#: eon/common/wsgi.py:284
#, python-format
msgid "Started child %s"
msgstr "已启动子项 %s"

#: eon/common/wsgi.py:297
msgid "eventlet 'poll' hub is not available on this platform"
msgstr "eventlet 'poll' hub 在此平台上不可用"

#: eon/common/wsgi.py:312
msgid "Starting single process server"
msgstr "正在启动单个进程服务器"

#: eon/common/wsgi.py:507
msgid "Malformed JSON in request body."
msgstr "请求正文中的 JSON 的格式不正确。"

#: eon/db/sqlalchemy/api.py:39
msgid ""
"Period in seconds after which SQLAlchemy should reestablish its "
"connection to the database."
msgstr ""
"SQLAlchemy 重新建立到数据库的连接"
"之前等待的时间(秒)。"

#: eon/db/sqlalchemy/api.py:42
msgid "The number of times to retry a connection to the SQLserver."
msgstr "连接到 SQL 服务器的重试次数。"

#: eon/db/sqlalchemy/api.py:45
msgid ""
"The amount of time to wait (in seconds) before attempting to retry the "
"SQL connection."
msgstr ""
"在尝试重试 SQL 连接之前等待"
"的时间(秒)。"

#: eon/db/sqlalchemy/api.py:48
msgid "A boolean that determines if the database will be automatically created."
msgstr "确定是否自动创建数据库的布尔值。"

#: eon/db/sqlalchemy/api.py:131
#, python-format
msgid ""
"Error configuring registry database with supplied sql_connection. Got "
"error: %s"
msgstr ""
"使用提供的 SQL 连接配置注册表数据库时出错。出现"
"错误:%s"

#: eon/db/sqlalchemy/api.py:141
msgid "auto-creating isc registry DB"
msgstr "正在自动创建 isc 注册表数据库"

#: eon/db/sqlalchemy/api.py:149
msgid "not auto-creating isc registry DB"
msgstr "未自动创建 isc 注册表数据库"

#: eon/db/sqlalchemy/api.py:190
#, python-format
msgid "SQL connection failed. %d attempts left."
msgstr "SQL 连接失败。还剩下 %d 次尝试。"

#: eon/db/sqlalchemy/api.py:255
#, python-format
msgid "No vCenter found with ID %s"
msgstr "找不到具有 ID %s 的 vCenter"

#: eon/db/sqlalchemy/api.py:622
msgid "Id not in sort_keys; is sort_keys unique?"
msgstr "Id 不在 sort_keys 中；sort_keys 是唯一的吗?"

#: eon/db/sqlalchemy/api.py:670
msgid "Unknown sort direction, must be 'desc' or 'asc'"
msgstr "未知排序方向，必须为“desc”或“asc”"

#: eon/db/sqlalchemy/api.py:747
#, python-format
msgid ""
"get_properties_for_resource id = %s\n"
" resource_id = %s\n"
" name = %s\n"
" type = %s\n"
" value = %s"
msgstr ""
"get_properties_for_resource id = %s\n"
" resource_id = %s\n"
" name = %s\n"
" type = %s\n"
" value = %s"

#: eon/db/sqlalchemy/api.py:777
#, python-format
msgid ""
"get_property_for_resource id = %s\n"
" resource_id = %s\n"
" name = %s\n"
" type = %s\n"
" value = %s"
msgstr ""
"get_property_for_resource id = %s\n"
" resource_id = %s\n"
" name = %s\n"
" type = %s\n"
" value = %s"

#: eon/db/sqlalchemy/api.py:796
#, python-format
msgid "update_resource_property %s %s %s %s"
msgstr "update_resource_property %s %s %s %s"

#: eon/db/sqlalchemy/api.py:832
#, python-format
msgid "update_resource_properties %s %s"
msgstr "update_resource_properties %s %s"

#: eon/db/sqlalchemy/api.py:841
#, python-format
msgid "update_resource_properties for %s %s returning %s"
msgstr "%s %s 的 update_resource_properties，正在返回 %s"

#: eon/db/sqlalchemy/api.py:847
#, python-format
msgid "Method _delete_resource_property %s %s"
msgstr "_delete_resource_property 方法 %s %s"

#: eon/db/sqlalchemy/api.py:856
#, python-format
msgid "Deleting property %s %s"
msgstr "正在删除属性 %s %s"

#: eon/db/sqlalchemy/api.py:860
#: eon/db/sqlalchemy/api.py:866
#, python-format
msgid "Error deleting property %s %s"
msgstr "在删除属性 %s %s 时出错"

#: eon/db/sqlalchemy/api.py:874
#, python-format
msgid "_delete_all_resource_properties %s"
msgstr "_delete_all_resource_properties %s"

#: eon/db/sqlalchemy/api.py:894
#, python-format
msgid "delete_resource_properties %s %s"
msgstr "delete_resource_properties %s %s"

#: eon/db/sqlalchemy/migration.py:35
msgid "database is not under migration control"
msgstr "未对数据库进行迁移控制"

#: eon/db/sqlalchemy/migration.py:49
#, python-format
msgid "Upgrading database to version %s"
msgstr "正在将数据库升级到版本 %s"

#: eon/db/sqlalchemy/migration.py:63
#, python-format
msgid "Downgrading database to version %s"
msgstr "正在将数据库降级到版本 %s"

#: eon/db/sqlalchemy/migration.py:76
msgid "database is already under migration control"
msgstr "已对数据库进行迁移控制"

#: eon/db/sqlalchemy/migrate_repo/schema.py:75
#, python-format
msgid "creating table %(table)s"
msgstr "正在创建表 %(table)s"

#: eon/db/sqlalchemy/migrate_repo/schema.py:81
#, python-format
msgid "dropping table %(table)s"
msgstr "正在删除表 %(table)s"

#: eon/notifier/publisher.py:15
msgid "The host name of the rabbitmq server"
msgstr "rabbitmq 服务器的主机名"

#: eon/notifier/publisher.py:17
msgid "The port on which the rabbitmq server is listening"
msgstr "rabbitmq 服务器正在侦听的端口"

#: eon/notifier/publisher.py:19
msgid "A boolean value indicating if the selected rabbitmq server uses SSL."
msgstr "指示选定 rabbitmq 服务器是否使用 SSL 的布尔值。"

#: eon/notifier/publisher.py:22
msgid "The user ID for authentication with rabbitmq."
msgstr "通过 rabbitmq 进行身份验证的用户 ID。"

#: eon/notifier/publisher.py:24
msgid ""
"The password that will be used for authentication with the rabbitmq "
"server."
msgstr ""
"通过 rabbitmq 服务器进行身份验证时"
"使用的密码。"

#: eon/notifier/publisher.py:27
msgid "The virtual host used in the rabbitmq connection."
msgstr "rabbitmq 连接中使用的虚拟主机。"

#: eon/notifier/publisher.py:29
msgid "Exchange name to use for connection when using rabbit strategy."
msgstr "使用 rabbit 策略时用于连接的交换名称。"

#: eon/notifier/publisher.py:32
#: eon/notifier/publisher.py:50
msgid "Topic to use for connection when using rabbit strategy."
msgstr "使用 rabbit 策略时用于连接的主题。"

#: eon/notifier/publisher.py:35
msgid "The maximum number of times to attempt to connect to the AMQP server."
msgstr "尝试连接到 AMQP 服务器的最大次数。"

#: eon/notifier/publisher.py:38
msgid ""
"This value multiplied by the number of connection attempts gives the "
"amount of time in seconds to sleep between connection attempts to the "
"AMQP server."
msgstr ""
"可以将该值乘以尝试的连接次数以得出"
"尝试连接到 AMQP 服务器之间"
"休眠的时间(秒)。"

#: eon/notifier/publisher.py:42
msgid ""
"The maximum amount of time to wait between connection attempts.  The "
"delay time will be the smaller of this value and the value of "
"<rabbit_retry_backoff> * <the number of failed connection attempts so "
"far>."
msgstr ""
"在连接尝试之间等待的最长时间。延迟"
"时间是该值和 "
"<rabbit_retry_backoff> * <the number of failed connection attempts so "
"far> 值之间的较小值。"

#: eon/notifier/publisher.py:138
#, python-format
msgid "Reconnecting to rabbitmq...topic: %s"
msgstr "正在重新连接到 rabbitmq...主题:%s"

#: eon/notifier/publisher.py:154
#, python-format
msgid "Attempting to publish message: %s"
msgstr "正在尝试发布消息:%s"

#: eon/notifier/publisher.py:161
#, python-format
msgid "Message : %s has been published"
msgstr "消息:已发布 %s"

#: eon/pavmm/utils.py:64
#, python-format
msgid "proc.stdout  :  %s"
msgstr "proc.stdout:%s"

#: eon/pavmm/utils.py:136
#, python-format
msgid ""
"Generating certificates & configurations... vCenter: %s, Resource-Name: "
"%s, ESX-Proxy: %s, Routing-Key: %s, Host IP-Address: %s"
msgstr ""
"正在生成证书和配置... vCenter:%s，资源名称:"
"%s，ESX 代理:%s，路由关键字:%s，主机 IP 地址:%s"

#: eon/pavmm/utils.py:143
msgid "Got neutron_password !"
msgstr "已获取 neutron_password!"

#: eon/pavmm/utils.py:154
msgid "Rabbitmq creds created"
msgstr "已创建 Rabbitmq 证书"

#: eon/pavmm/utils.py:168
msgid "All require directories created"
msgstr "已创建所需的所有目录"

#: eon/pavmm/utils.py:185
#, python-format
msgid "Conf file written %s"
msgstr "已写入配置文件 %s"

#: eon/pavmm/utils.py:187
#, python-format
msgid "Compute hostname: %s"
msgstr "计算主机名:%s"

#: eon/pavmm/utils.py:194
msgid "RabbitMQ, Postgres certs created"
msgstr "RabbitMQ，已创建 Postgres 证书"

#: eon/pavmm/utils.py:202
#, python-format
msgid "Deleted: Rabbitmq_user = %s"
msgstr "已删除:Rabbitmq_user = %s"

#: eon/pavmm/utils.py:212
#, python-format
msgid "Creating VM...ESX-Proxy: %s, Resource: %s, vCenter: %s"
msgstr "正在创建 VM...ESX 代理:%s，资源:%s，vCenter:%s"

#: eon/pavmm/cert_config/compute_node_certs.py:52
#, python-format
msgid "Writing temporary certificate...Compute node-name: %s, Config: %s"
msgstr "正在写入临时证书...计算节点名称:%s，配置:%s"

#: eon/pavmm/cert_config/compute_node_certs.py:56
#, python-format
msgid "Compute Certs Location: %s "
msgstr "计算证书位置:%s "

#: eon/pavmm/cert_config/compute_node_certs.py:114
#, python-format
msgid "unconfig cert for %s"
msgstr "取消配置 %s 的证书"

#: eon/pavmm/cert_config/postgresql_config.py:21
msgid "Setting PostgresConfig server-side config"
msgstr "正在设置 PostgresConfig 服务器端配置"

#: eon/pavmm/cert_config/postgresql_config.py:33
msgid "Setting PostgresConfig client-side config"
msgstr "正在设置 PostgresConfig 客户端配置"

#: eon/pavmm/cert_config/rabbitmq_config.py:22
msgid "Setting RabbitMQConfig server-side config"
msgstr "正在设置 RabbitMQConfig 服务器端配置"

#: eon/pavmm/cert_config/rabbitmq_config.py:54
msgid "Setting RabbitMQConfig client-side config"
msgstr "正在设置 RabbitMQConfig 客户端配置"

#: eon/vmware/vshield_client.py:28
#, python-format
msgid "REQ URL: %s\n"
msgstr "请求 URL:%s\n"

#: eon/vmware/vshield_client.py:38
#, python-format
msgid "REQ: %s\n"
msgstr "请求:%s\n"

#: eon/vmware/vshield_client.py:40
#, python-format
msgid "REQ BODY: %s\n"
msgstr "请求正文:%s\n"

#: eon/vmware/vshield_client.py:59
#, python-format
msgid "Error in executing vshield api for rest url %s, Cause : %s"
msgstr "为 rest url %s 执行 vshield api 时出错，原因:%s"

#: eon/vmware/vshield_client.py:69
#, python-format
msgid "RESP:%s\n"
msgstr "响应:%s\n"

#: eon/vmware/vshield_client.py:71
#, python-format
msgid "RESP BODY:%s\n"
msgstr "响应正文:%s\n"

#: eon/vmware/vshield_client.py:74
msgid "Could not validate vshield credentials"
msgstr "无法验证 vshield 凭据"

